language: node_js
node_js:
- '5'
branches:
  only:
  - master
install: npm install -g gitbook-cli
before_script: gitbook install
script: gitbook build
after_success:
- bash deploy.sh
env:
  global:
  - secure: I/kt/uXh1Iz6seQFT7CwyBnErAhlY2djkQ+UK1KWhbKikzkAVvG+uPUVj3dJ79J1LgP1cGTmA2n2Zhjm6Zyzn6YB8Y6rv1ZwQB9m7HQ4Kq1MuzdzjtGhSC486KPYBT97QGDlUlCd7qmAyDVFf+cJ3FyNqbj0q7Z4sNAqM436Vp2QFvIwgCaegJZORPTRnOFssfmuDtbyplOjgqqfnnWe8OtU8llJpObqTmj3m74kOMATEaPwrKAZ6JPTzyqBHu5NThLg6RnCmiNQcJn2FlEe2vZvJRFTV1eBqLcdxzCtBICwp6w61OeYb6YZLSoloSOcsIY81BbaEg0dtLa6jBPXpsj+N0w31aqc+L1RYmfQE1RPQSJIkfVU7KuWU+qihTq21bcuXaVD3KUbSgPGSEDmxC4kQYD85NvPg64wwmmmgPPmHSCwgbenX89zer9sOrPWHuUzFRHCcE7MisDMzqCUBZHHdh98DQeFbLnqI7Ar0XXysLuzTS6AtMjEkc3Ufcjg+gkjgweBKP3EMHW9wJpZyVUS31BJCJ8W0DkMXlE8bWzO+5fLfbFwwLhhcijSgZhTARtEM05VQMKqd9gSNbeG2a/Xuk4djviq0DiJDj2UuwTkIAHVOkPah9zMx6xwF+BSul/VPT0TABUxA+kfYNgy8WA8jcfe25GHIrtEIblnhxc=
