language: node_js
node_js:
- '5'
branches:
  only:
  - master
install: npm install -g gitbook-cli
before_script: gitbook install
script: gitbook build
after_success:
- bash deploy.sh
env:
  global:
  - secure: SSeVngO2VRa4Yqmv2ttLeLGFhLzFViCkpdzWHXV1WgESGl1LDheobTV0Ls/5T95aRnDNwVfwQo1wDVd7Mxs6qQXsjE/p6EeCdAIW4ZnM0CmK487D2TIY3nAT0TtoufxolTb7eSDh1M1gtvXWFJIg+OZI0U5RMMDcZjBKo0a15sv6OaNacGjzIxp1ns5rsNfuyJkrzDeMx7cn8NqMLOniop6pejDLvZOiVL2l1yq5cm1+JFWm9naqI8ZQaqWCFmLOiOykip+bIpKrlO8eCppgc9Jzeae74fHC03NMby1R8Sjrm/gWG7ZAlkoCz2yxjSUDs0SXMTwzOWa5whSL6XysjanDIBhgKh3nXr8UsYqNz6cdpI62S/Jfe55Sg4xWTQmBn2+BdYTRWXZbgVFAPklbtSv/rfiPSJdhKfDBxMQW+r8j4oYem34FCMi/kZwjckxelbHSFGvgcgzXCrMARF/o+m57R6na9obk8Jjq3hZZy06mWcDfJX6wsRJliBpRihEZPhvJQB7ykipCYRHgJ+9kgOx12zHmBY7ZZWfNklrk3x7xBPVuqOVGZ1fH2aR+xmZ2OPd1WjOqwukSmDVHagQ4rmFOHDK2+BwbPfazklRPRFQd21S+dsmmnQfOIm8cImTE3bLGXuTYSubLzgXUbzZtooQ9QH275+5RqdgE2Q3Ufxg=
  - GH_REF: x-oauth-basic@github.com/beader/github-gitbook.git
